package greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import com.google.gson.annotations.SerializedName;
// KEEP INCLUDES END
/**
 * Entity mapped to table "AD_TYPE".
 */
public class AdType {

    // KEEP FIELDS - put your custom fields here

    public static final String TYPE_SHORT_TERM = "shortterm";
    public static final String TYPE_SHARING = "sharing";
    public static final String TYPE_SALE = "sale";
    public static final String TYPE_RENTAL = "rental";
    public static final String TYPE_PARKING = "parking";
    public static final String TYPE_NEW_DEVELOPMENT = "new_development";
    public static final String TYPE_COMMERCIAL = "commercial";

    private String name;
    @SerializedName("desc")
    private String description;
    @SerializedName("desc_plural")
    private String descriptionPlural;
    @SerializedName("desc_short")
    private String descriptionShort;

    // KEEP FIELDS END

    public AdType() {
    }

    public AdType(String name) {
        this.name = name;
    }

    public AdType(String name, String description, String descriptionPlural, String descriptionShort) {
        this.name = name;
        this.description = description;
        this.descriptionPlural = descriptionPlural;
        this.descriptionShort = descriptionShort;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescriptionPlural() {
        return descriptionPlural;
    }

    public void setDescriptionPlural(String descriptionPlural) {
        this.descriptionPlural = descriptionPlural;
    }

    public String getDescriptionShort() {
        return descriptionShort;
    }

    public void setDescriptionShort(String descriptionShort) {
        this.descriptionShort = descriptionShort;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
