package greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import com.google.gson.annotations.SerializedName;
// KEEP INCLUDES END
/**
 * Entity mapped to table "AD_TYPE".
 */
public class AdType {

    // KEEP FIELDS - put your custom fields here

    private String name;
    @SerializedName("desc_short")
    private String descriptionShort;
    @SerializedName("desc")
    private String description;
    // KEEP FIELDS END

    public AdType() {
    }

    public AdType(String name) {
        this.name = name;
    }

    public AdType(String name, String descriptionShort, String description) {
        this.name = name;
        this.descriptionShort = descriptionShort;
        this.description = description;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescriptionShort() {
        return descriptionShort;
    }

    public void setDescriptionShort(String descriptionShort) {
        this.descriptionShort = descriptionShort;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
