package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Pagination;
import greendao.Advertisement;
import greendao.Feature;

import greendao.PaginationDao;
import greendao.AdvertisementDao;
import greendao.FeatureDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig paginationDaoConfig;
    private final DaoConfig advertisementDaoConfig;
    private final DaoConfig featureDaoConfig;

    private final PaginationDao paginationDao;
    private final AdvertisementDao advertisementDao;
    private final FeatureDao featureDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        paginationDaoConfig = daoConfigMap.get(PaginationDao.class).clone();
        paginationDaoConfig.initIdentityScope(type);

        advertisementDaoConfig = daoConfigMap.get(AdvertisementDao.class).clone();
        advertisementDaoConfig.initIdentityScope(type);

        featureDaoConfig = daoConfigMap.get(FeatureDao.class).clone();
        featureDaoConfig.initIdentityScope(type);

        paginationDao = new PaginationDao(paginationDaoConfig, this);
        advertisementDao = new AdvertisementDao(advertisementDaoConfig, this);
        featureDao = new FeatureDao(featureDaoConfig, this);

        registerDao(Pagination.class, paginationDao);
        registerDao(Advertisement.class, advertisementDao);
        registerDao(Feature.class, featureDao);
    }
    
    public void clear() {
        paginationDaoConfig.getIdentityScope().clear();
        advertisementDaoConfig.getIdentityScope().clear();
        featureDaoConfig.getIdentityScope().clear();
    }

    public PaginationDao getPaginationDao() {
        return paginationDao;
    }

    public AdvertisementDao getAdvertisementDao() {
        return advertisementDao;
    }

    public FeatureDao getFeatureDao() {
        return featureDao;
    }

}
