package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FEATURE".
 */
public class Feature {

    private Long id;
    private Long advertisementId;
    private String description;

    public Feature() {
    }

    public Feature(Long id) {
        this.id = id;
    }

    public Feature(Long id, Long advertisementId, String description) {
        this.id = id;
        this.advertisementId = advertisementId;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAdvertisementId() {
        return advertisementId;
    }

    public void setAdvertisementId(Long advertisementId) {
        this.advertisementId = advertisementId;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
