package greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "FEATURE".
 */
public class Feature {

    private Long id;
    private Long advertisementId;
    private String description;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Feature() {
    }

    public Feature(Long id) {
        this.id = id;
    }

    public Feature(Long id, Long advertisementId, String description) {
        this.id = id;
        this.advertisementId = advertisementId;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAdvertisementId() {
        return advertisementId;
    }

    public void setAdvertisementId(Long advertisementId) {
        this.advertisementId = advertisementId;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
