package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PAGINATION".
 */
public class Pagination {

    private Long id;
    private Long total;
    private Long perPage;
    private Long numPages;
    private Long currentPage;
    private Long firstOnPage;
    private Long lastOnPage;

    public Pagination() {
    }

    public Pagination(Long id) {
        this.id = id;
    }

    public Pagination(Long id, Long total, Long perPage, Long numPages, Long currentPage, Long firstOnPage, Long lastOnPage) {
        this.id = id;
        this.total = total;
        this.perPage = perPage;
        this.numPages = numPages;
        this.currentPage = currentPage;
        this.firstOnPage = firstOnPage;
        this.lastOnPage = lastOnPage;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTotal() {
        return total;
    }

    public void setTotal(Long total) {
        this.total = total;
    }

    public Long getPerPage() {
        return perPage;
    }

    public void setPerPage(Long perPage) {
        this.perPage = perPage;
    }

    public Long getNumPages() {
        return numPages;
    }

    public void setNumPages(Long numPages) {
        this.numPages = numPages;
    }

    public Long getCurrentPage() {
        return currentPage;
    }

    public void setCurrentPage(Long currentPage) {
        this.currentPage = currentPage;
    }

    public Long getFirstOnPage() {
        return firstOnPage;
    }

    public void setFirstOnPage(Long firstOnPage) {
        this.firstOnPage = firstOnPage;
    }

    public Long getLastOnPage() {
        return lastOnPage;
    }

    public void setLastOnPage(Long lastOnPage) {
        this.lastOnPage = lastOnPage;
    }

}
